channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12.3
  - snakemake=8.14.0
  - biopython=1.83
  - matplotlib=3.8.4
  - pandas=2.2.2
  - numpy=1.26.4
  - snakemake-executor-plugin-slurm=0.6.0
